/*
 * Giữ các từ ghép tiếng Việt trên cùng một dòng khi chữ xuống dòng
 * (ví dụ tránh "an / ninh", "đoàn / kết"): khoảng trắng bên trong từ ghép
 * được thay bằng khoảng trắng không ngắt (U+00A0).
 * Danh sách gồm các từ ghép xuất hiện trong bài thuyết trình.
 */
const COMPOUNDS = [
  "đại gia đình",
  "an ninh",
  "an sinh",
  "an toàn",
  "bản sắc",
  "bảo đảm",
  "bảo vệ",
  "bình đẳng",
  "cấp bách",
  "chia cắt",
  "chiến lược",
  "chính sách",
  "chính trị",
  "chủ nghĩa",
  "chủ trương",
  "chủ yếu",
  "cơ bản",
  "cơ sở",
  "công nhân",
  "cộng đồng",
  "cư trú",
  "cương lĩnh",
  "dân cư",
  "dân số",
  "dân tộc",
  "địa bàn",
  "đa dạng",
  "đầu tư",
  "đậm đà",
  "độc lập",
  "đoàn kết",
  "đồng bào",
  "đồng nhất",
  "đồng thời",
  "gắn bó",
  "giúp nhau",
  "góp phần",
  "hệ thống",
  "hiện nay",
  "hình thành",
  "hoàn toàn",
  "khác nhau",
  "khách quan",
  "kinh tế",
  "lãnh thổ",
  "lâu dài",
  "lâu đời",
  "liên hiệp",
  "mác – lênin",
  "miền núi",
  "ngôn ngữ",
  "nhà nước",
  "ổn định",
  "phân bố",
  "phát triển",
  "phong phú",
  "phương thức",
  "quan trọng",
  "quản lý",
  "quốc gia",
  "quốc phòng",
  "quy mô",
  "sinh hoạt",
  "sức mạnh",
  "tách biệt",
  "tăng cường",
  "tâm lý",
  "thậm chí",
  "thiểu số",
  "thống nhất",
  "tiên tiến",
  "tôn trọng",
  "tồn tại",
  "toàn diện",
  "tổ quốc",
  "tộc người",
  "trách nhiệm",
  "trật tự",
  "trình độ",
  "truyền thống",
  "tự giác",
  "tự quyết",
  "tương trợ",
  "ưu tiên",
  "văn hóa",
  "vị trí",
  "việt nam",
  "xã hội",
  "xen kẽ",
  "xu hướng",
  "ý thức",
  // Thêm cho các màn hình tách mới.
  "chênh lệch",
  "chín muồi",
  "con đường",
  "đặc điểm",
  "đặc trưng",
  "đồng đều",
  "giống nhau",
  "lĩnh vực",
  "liên hệ",
  "lựa chọn",
  "nhấn mạnh",
  "nhiệm vụ",
  "nhu cầu",
  "phân tán",
  "phong kiến",
  "quan điểm",
  "quyết định",
  "sản xuất",
  "sinh sống",
  "thành lập",
  "thay thế",
  "toàn bộ",
  "tư bản",
  "tự nguyện",
  "tương đối",
  "vận mệnh",
  "xác lập",
];

const COMPOUND_PATTERN = new RegExp(
  `(?<!\\p{L})(?:${COMPOUNDS.join("|")})(?!\\p{L})`,
  "giu",
);

export function keepWords(text: string): string {
  return text.replace(COMPOUND_PATTERN, (match) =>
    match.replaceAll(" ", " "),
  );
}
